include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    sort_pub_dependencies: false
    depend_on_referenced_packages: false
    constant_identifier_names: false
    annotate_overrides: false
    overridden_fields: false

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
