name: gestiona3w
description: Gestion Remota
version: 1.0.1+3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture
  get: ^4.6.5
  dartz: ^0.10.1

  # Responsive
  flutter_screenutil: ^5.7.0

  # Cupertino
  cupertino_will_pop_scope: ^1.2.0
  cupertino_icons: ^1.0.2

  # Preferences
  flutter_secure_storage: ^8.0.0

  # Animations
  animate_do: ^3.0.2
  lottie: ^2.4.0

  # Date Format
  intl: ^0.18.0

  # Google Maps
  google_maps_flutter: ^2.2.8

  # Api Rest
  http: ^1.0.0

  # BBDD
  realm: ^1.3.0

  # Check Internet
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: 2.8.3
  build_runner: ^2.4.5
  change_app_package_name: ^1.1.0

flutter:
  #generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/map_style/
    - assets/lotties/

flutter_intl:
  enabled: true
  main_locale: es